application: winepumper
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /javascripts
  static_dir: javascripts
  
    
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /wine
  script: wine.py

  
- url: /
  static_files: static_files/index.html
  upload: static_files/index.html
  expiration: "15m"
  
  
- url: /users
  script: user.py
